### ISSUE TITLE
Zero byte system updates and system update call

### ISSUE THREAD

**Issue by mattvj** [martzcodes/NodeAlarmProxy#16]
Should the updatesystem action on line 215 point to the updatesystem function? Also should all zero bytes updatesystem actions be ignored as per line 201?

**Comment by martzcodes** [comment]
@mattvj Yes, probably.  You're the first person to point it out in ~3 years... so nice catch.  Is something in particular not working for you?

**Comment by mattvj** [comment]
@martzcodes Was trying to get the program 1 and 2 data from envisalink (ie 2-wire fire alarm) .  These commands are currently getting put into a partition user record, but because the bytes are zero it gets dropped.

**Comment by dustindclark** [comment]
@martzcodes we've tested downstream and merged.  Could you please publish to NPM?  Thanks.

**Comment by martzcodes** [comment]
Published to NPM
